### ISSUE TITLE
Serverless-AWS Deploy: outstanding issues

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/deploy-target-ci#826] opened 2023-05-08 03:47 UTC
## 1. Site entry via non-home Routes do not fetch+render
Go directly to this page:
- https://d1nqrl4z14qxd1.cloudfront.net/blog-post/1
- empty (no errors)

There is no content. In browser network tab, there is no fetch.

If you first navigate to the home page and click the link, everything works:
- https://d1nqrl4z14qxd1.cloudfront.net
- click "what is the meaning of life"
- navigation is successful to https://d1nqrl4z14qxd1.cloudfront.net/blog-post/1 and fetch + render is successful

My guess is this is a Cloudfront issue where cache-hit=true is messing with the Redwood Router.

We've been using Serverless Lift Static-Site plugin — I have no idea how long this behavior has been broken. I tried using the Serverless Lift plugin for SPA in #825 which didn't seem to help or change behavior at all:
https://github.com/getlift/lift/blob/master/docs/single-page-app.md

Video shows working example first. Then broken behavior:
https://user-images.githubusercontent.com/2951/236730309-9fbc357f-d2cf-4212-ae9f-1c90af3ce972.mp4

## 2. .env.production doesn't work after using the first time for --first-run
Although the documentation requires creating and using `.env.production`, this file is never accessed when deploying via `yarn rw deploy serverless`. See:
- https://github.com/redwoodjs/redwood/issues/4548

Additionally, it doesn't seem to work on subsequent uses of --first-run. See:
- https://github.com/redwoodjs/redwood/issues/5785

I suggest the easiest fix is to remove use of .env.production in --first-run and update Docs accordingly

## 3. Update Serverless Deploy Docs: Custom Functions
Provide instructions about adding custom functions to serverless.yml

**Comment by gilliardmacedo** [comment] 2023-05-22 22:12
I can reproduce the behavior you described, but I can see this error accessing directly the post route:
<img width="517" alt="Screenshot 2023-05-22 at 19 03 08" src="https://github.com/redwoodjs/deploy-target-ci/assets/26877564/e15e3ccc-55df-416b-a44d-8ffa52fcbca5">
In this state, even if I click in the title and try to open a post, I got the same blank page. Had to refresh the home to get router working again.

Please forgive me if it's not related, but I had to move to spa plugin too, since static site plugin is broken because of changes in the S3 Bucket creation policy. SPAs have, in the 'Error page' section of CloudFront, a redirect to the index with status code 200 in case of errors(directly accessed routes will cause errors because will firstly try to find a resource in the S3 bucket with that name). This redirect is enough to get stuff working. But seems to be different if the app have prerendered routes.

**Comment by thedavidprice** [comment] 2023-05-23 23:12
Thank you @gilliardmacedo 

This is very helpful:
> Please forgive me if it's not related, but I had to move to spa plugin too, since static site plugin is broken because of changes in the S3 Bucket creation policy. SPAs have, in the 'Error page' section of CloudFront, a redirect to the index with status code 200 in case of errors(directly accessed routes will cause errors because will firstly try to find a resource in the S3 bucket with that name). This redirect is enough to get stuff working. But seems to be different if the app have prerendered routes.

**Comment by Josh-Walker-GM** [comment] 2024-06-10 20:17
We've deprecated support for aws-serverless deployment. I'm going to close this issue now.

**Closed by Josh-Walker-GM** 2024-06-10 20:17 UTC
